Udemy: Deep Learning A-Z
Artificial Neural Networks
The dataset is bank customer data and we have to predict whether customer will leave the bank or not.
Dataset: Churn_Modelling 
Number of observations: 10000    

In [1]:
# Classification template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from sklearn import preprocessing


In [2]:
#PART 1: DATA PREPROCESSING
#Import dataset 
#Set X equal to independent variables in dataset and y equals to final column which is prediction 
dataset = pd.read_csv('Churn_Modelling.csv')
#dataset.shape()
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [3]:
#Encoding the categorical data (here gender and country of the customer)
#Label Encoding of "Gender Coloumn" 
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X [:,2] = le.fit_transform(X[:,2])  #2th coloumn contains gender information
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Now we have to encode the geogrophy coloumn. But we cannot encode it simply as 1 and 0 as it may loss the information while 
making the equation. Thus we need to use "One Hot Encoder" here.
Here we have encoded the countries as
France : 1 0 0 
Spain  : 0 0 1
Germany: 0 1 0

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough') #[1] means column 1 == Gepgraphy
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [5]:
#Split the Dataset into Training and Testing Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
#Feature Scaling is very very important in deep learning.
#It is fundamental step in ANN or Deep Learning
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [7]:
#Part 2: BUILDING THE ANN
#2.1 : Initializing the ANN
import keras
ann = tf.keras.models.Sequential()

Using TensorFlow backend.


In [8]:
#2.2 Adding Input and the first hidden layer
#We will add fully connected hidden layer and input layer get automatically created
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [9]:
#2.3 Adding second hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [10]:
#2.4 Adding output layer
#Since y is having two classes, thus number of neurons in output layer is 1
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [11]:
#PART 3: TRAINING THE ANN
#3.1 Compile the ANN
ann.compile(optimizer ='Adam' ,loss ='binary_crossentropy' ,metrics =['accuracy']) #Plz study other types of parameters

In [13]:
#3.2 Training the ANN on training set
ann.fit(X_train, y_train, batch_size = 32,epochs = 200 )#batch size generally used is 32 # study epoch
#we need number of epochs to learn the ANN over time and in more accurate manner
#accuarcy increases as epochs

Train on 8000 samples
Epoch 1/200
8000/8000 [==============================] - 9s 1ms/sample - loss: 0.3337 - accuracy: 0.8644
Epoch 2/200
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3334 - accuracy: 0.8631
Epoch 3/200
8000/8000 [==============================] - 1s 63us/sample - loss: 0.3332 - accuracy: 0.8629
Epoch 4/200
8000/8000 [==============================] - 1s 76us/sample - loss: 0.3332 - accuracy: 0.8636s - loss: 0.3
Epoch 5/200
8000/8000 [==============================] - 1s 67us/sample - loss: 0.3334 - accuracy: 0.8644
Epoch 6/200
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3329 - accuracy: 0.8654
Epoch 7/200
8000/8000 [==============================] - 0s 56us/sample - loss: 0.3331 - accuracy: 0.8649
Epoch 8/200
8000/8000 [==============================] - 1s 66us/sample - loss: 0.3331 - accuracy: 0.8645
Epoch 9/200
8000/8000 [==============================] - 1s 73us/sample - loss: 0.3329 - accuracy: 0.8639
Epoch 10/200

8000/8000 [==============================] - 1s 71us/sample - loss: 0.3305 - accuracy: 0.8641
Epoch 78/200
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3303 - accuracy: 0.8648
Epoch 79/200
8000/8000 [==============================] - 1s 63us/sample - loss: 0.3302 - accuracy: 0.8646
Epoch 80/200
8000/8000 [==============================] - 0s 54us/sample - loss: 0.3304 - accuracy: 0.8644
Epoch 81/200
8000/8000 [==============================] - 0s 62us/sample - loss: 0.3306 - accuracy: 0.8645
Epoch 82/200
8000/8000 [==============================] - 0s 56us/sample - loss: 0.3305 - accuracy: 0.8645
Epoch 83/200
8000/8000 [==============================] - 0s 54us/sample - loss: 0.3304 - accuracy: 0.8643
Epoch 84/200
8000/8000 [==============================] - 1s 63us/sample - loss: 0.3306 - accuracy: 0.8630
Epoch 85/200
8000/8000 [==============================] - 0s 54us/sample - loss: 0.3306 - accuracy: 0.8645
Epoch 86/200
8000/8000 [==========================

8000/8000 [==============================] - 1s 67us/sample - loss: 0.3296 - accuracy: 0.8640
Epoch 154/200
8000/8000 [==============================] - 1s 85us/sample - loss: 0.3293 - accuracy: 0.8649
Epoch 155/200
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3292 - accuracy: 0.8652
Epoch 156/200
8000/8000 [==============================] - 0s 54us/sample - loss: 0.3289 - accuracy: 0.8648
Epoch 157/200
8000/8000 [==============================] - 1s 65us/sample - loss: 0.3291 - accuracy: 0.8648
Epoch 158/200
8000/8000 [==============================] - 0s 55us/sample - loss: 0.3295 - accuracy: 0.8649
Epoch 159/200
8000/8000 [==============================] - 0s 62us/sample - loss: 0.3293 - accuracy: 0.8641
Epoch 160/200
8000/8000 [==============================] - 1s 68us/sample - loss: 0.3292 - accuracy: 0.8658
Epoch 161/200
8000/8000 [==============================] - 0s 55us/sample - loss: 0.3285 - accuracy: 0.8650
Epoch 162/200
8000/8000 [=================

PART 4: PREDICTION
    HOMEWORK

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France  ====> 1 0 0

Credit Score: 600

Gender: Male       ====> 1

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

In [14]:
#PART 4: Making the predictions and evaluating the model
#4.1 Predicting the result of single observation
#Input to the predict method must always be 2d array
#Inputs must be scaled in same way as scaleede for training set
#Use fit_transform for traing while only transform for test set
print(ann.predict(sc.transform([[1,0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))) # this will give probability of customer leabing the bank

#Thus we can use the 
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

[[0.02530829]]
[[False]]


In [15]:
#4.2 Prediciting the test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate(y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)))

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
#4.3 Calculate confusion matrix and accuracy
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)